### ISSUE TITLE
wont make any filter no matter what the setting are, including default.

### ISSUE THREAD

**Issue by maxtraxv3** [flapanther33781/poe-filter#26]
always out puts this every time:
`Vial section complete.
Strictness filter is 10 and booShowT11 is True
Traceback (most recent call last):
  File "C:\Users\maxtr\Downloads\poe-filter-main\poe-filter-main\scripts\010-main.py", line 16, in <module>
    task9 = __import__('040-create-filter')
  File "C:\Users\maxtr\Downloads\poe-filter-main\poe-filter-main\scripts\040-create-filter.py", line 10394, in <module>
    func_heist()
  File "C:\Users\maxtr\Downloads\poe-filter-main\poe-filter-main\scripts\040-create-filter.py", line 1042, in func_heist
    str_MinimapIcon = row[18]
IndexError: list index out of range`

**Comment by flapanther33781** [comment]
Hi mate.  Thanks for the notification.  I'm out of town visiting my father for the holiday, should be back home on the 3rd or 4th, will check on it then.  IIRC I'd already seen that fixed it, and added a new feature or two, just hadn't uploaded it to Github yet.  I don't have Python on this laptop, so rather than reinvent the wheel please just bear with me until I get home again.

In the meantime if you want to get a feel for how the filter looks/behaves in the root of the repository are files named `3.16-3-10-10-1-1-1-0-0-0.filter` and `3.16-3-10-10-1-1-1-0-0-0-INV.filter`.  These are filters created with the tool, but set to the most loose setting - shows basically everything, as you would use it if you were starting a new league in Act 1.

**Comment by flapanther33781** [comment]
Okay, I've uploaded my current files.  Delete what you downloaded, redownload and try again.  Let me know if you have any issues.

**Comment by maxtraxv3** [comment]
odd showing armour scrap are better then chaos orbs?
using this filter https://ghostbin.com/goW2z
![image](https://user-images.githubusercontent.com/12743527/148176095-e1480c45-6803-4f32-ae18-b8f23322061f.png)
![image](https://user-images.githubusercontent.com/12743527/148176250-7c47e0ef-f652-4655-b7e4-1e1036e83043.png)

**Comment by flapanther33781** [comment]
That coloring does not mean something is valuable, that's the "ERROR" color given to items that aren't being highlighted by other sections of the filter but also are not being explicitly hidden (I hide things explicitly rather than do a blanket 'hide everything' exactly to catch what could be problems/errors like this).

I have seen this in the past, both with Armourer's Scraps and other items, too.  There's a gap between what poe.ninja is doing and what I thought they were doing, and I need to come up with a solution for it.  I only learned about this stuff this league and just haven't had time to code a solution yet.

The problem was that I didn't understand how poe.ninja worked.  I thought he maintained a database of every item in the game, but he doesn't.  He only lists items in his database if the item is actually listed on the official PoE trade site.  So if there are no Armourer's Scraps listed on the official page, then they won't be listed in poe.ninja's data, and then it won't show up in my tool either.  Or, if poe.ninja is having some transient error, my tool does not currently recover from that.

What I'm going to do is use this league's filter as a baseline database, then for every league past this I'll have to poll poe.ninja for data and only use that to add/update the baseline database, not solely rely on it to have everything in it.

For the moment you can manually add the Armourer's Scraps to the file named `z030_assigned-values.csv`, then run the filter generation again.  Check the FAQ for a link to a video with instructions.  The instructions are how to override a setting, but you can probably figure out how to add an item in there as well.  Just copy a line that has the correct formatting for the same tier item you want the Armourer's Scraps to be.

**Comment by flapanther33781** [comment]
Were you able to edit the spreadsheet to take care of that?

I didn't play much for the last week or two, but did today.  I saw a number of very strange map drops.  Some were pink (like that missing one), one was gray (which should never happen for a non-unique map), and one was white like a T1 drop.  All three maps were normal, low tier maps.  I've been working on this tool for two leagues now and never had this happen, so I have no idea what's going on with that.  Will probably take some time to troubleshoot.
